#!/bin/sh

dir=${PASSWORDS:="$HOME/passwords"}

creset='\033[0m'
cdir='\033[1;36m'
ctitle='\033[1m'

# List files in $1 in a formatted format using $2 as the prefix of each printed
# line, recursing directories and appending to $2 for each cycle to create an
# indentation effect. If present, the ".enc" prefix is removed from file names.
list() {
	for f in "$1"/*; do
		b=$(basename "$f")

		if [ -d "$f" ]; then
			printf    "$2├── ${cdir}$b${creset}\n"
			list "$f" "$2│   "
		elif [ -f "$f" ]; then
			printf    "$2├── ${b%.enc}\n"
		fi
	done
}

printf "${ctitle}Passwords${creset}\n"
list "$dir" ""
