#!/bin/sh

dir=${SECRETS:="$HOME/secrets"}

creset='\033[0m'
cdir='\033[1;36m'
ctitle='\033[1m'

# Prints $1 to stderr and exits with return code 1.
die() {
	echo "$1" >&2
	exit 1
}

# Dies printing usage.
usage() {
	die "Usage: $0 list"
}

# List files ending in ".enc" in $1 in a formatted format using $2 as the
# prefix of each printed line, recursing directories and appending to $2 for
# each cycle to create an indentation effect. The ".enc" prefix is removed from
# file names.
list() {
	for f in "$1"/*; do
		b=$(basename "$f")

		if [ -d "$f" ]; then
			printf    "$2|- ${cdir}$b${creset}\n"
			list "$f" "$2|  "
		elif [ -f "$f" ]; then
			case "$b" in
			*.enc)
				printf    "$2|- ${b%.enc}\n"
				;;
			esac
		fi
	done
}

case "$1" in
list)
	printf "${ctitle}Secrets${creset}\n"
	list "$dir" ""
	;;
*)
	usage
esac
